server:
  port: 80
# 1~65535

spring:
    datasource:
        name: test
        url: jdbc:mysql://120.79.62.176:3306/bos32?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: admin
        password: 232012
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/template/
        encoding: UTF-8
        mode: HTML5
        content-type: text/html
        suffix: .html
devtools:
        restart: 
            enabled: true
mybatis:
  type-aliases-package: cn.overseachem.erp.pojo
  mapper-locations: classpath:mapper/*.xml

